---
include:
   - board: nice_nano_v2
    shield: corne_peripheral_left hammerbeam_display
    artifact-name: corne_peripheral_left
  - board: nice_nano_v2
    shield: corne_peripheral_right hammerbeam_display
    artifact-name: corne_peripheral_right